name: test on windows

on:
  push:
    branches: [ master, develop, 'feature/**' ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            preset: ci-windows-x64-debug
          - os: windows-latest
            preset: ci-windows-x64-release
          - os: windows-11-arm
            preset: ci-windows-arm64-debug
          - os: windows-11-arm
            preset: ci-windows-arm64-release

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Test
      run: ctest --preset ${{ matrix.preset }}

